title: My GitHub Pages Site
description: A simple site built with Jekyll
author: Vladimir Rife
theme: jekyll-theme-minimal
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
